DROP TABLE IF EXISTS GLOBAL_SETTING;
DROP TABLE IF EXISTS FRAGMENT;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS FILE;
DROP TABLE IF EXISTS TAG2TAG;
DROP TABLE IF EXISTS TAG2FRAGMENT;
DROP TABLE IF EXISTS FRAGMENT2FRAGMENT;
